name: Publish Extension

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g vsce

      - name: Package and Publish
        run: |
          vsce package
          vsce publish minor -p ${{ secrets.VSCE_PAT }}
